/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemrogramanjaringan;

import java.text.NumberFormat;
import java.util.StringTokenizer;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Vq Fikky
 */
public class KelasIP extends javax.swing.JFrame {
    
    public int oktett1;
    public int oktett2;
    public int oktett3;
    public int oktett4;
    public String result;
    

    /**
     * Creates new form KelasIP
     */
    public KelasIP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oktet1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnDetectIP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ResultClassIP = new javax.swing.JLabel();
        oktet2 = new javax.swing.JTextField();
        oktet3 = new javax.swing.JTextField();
        oktet4 = new javax.swing.JTextField();
        btnPindah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        oktet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oktet1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mendeteksi Kelas IP Address");

        BtnDetectIP.setText("Detect");
        BtnDetectIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDetectIPActionPerformed(evt);
            }
        });

        jLabel2.setText("IP Address");

        ResultClassIP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ResultClassIP.setText("jLabel3");

        oktet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oktet2ActionPerformed(evt);
            }
        });

        oktet3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oktet3ActionPerformed(evt);
            }
        });

        oktet4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oktet4ActionPerformed(evt);
            }
        });

        btnPindah.setText("Pindah Halaman");
        btnPindah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPindahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oktet1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oktet2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oktet3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oktet4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResultClassIP)
                            .addComponent(BtnDetectIP)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnPindah)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(oktet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oktet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oktet3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oktet4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnDetectIP)
                .addGap(61, 61, 61)
                .addComponent(ResultClassIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnPindah)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oktet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oktet1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oktet1ActionPerformed

    private void oktet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oktet2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oktet2ActionPerformed

    private void oktet3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oktet3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oktet3ActionPerformed

    private void oktet4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oktet4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oktet4ActionPerformed

    private void BtnDetectIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDetectIPActionPerformed
        
        if (oktet1.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Oktet 1 masih kosong");
            return;
        }
        else if (oktet2.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Oktet 2 masih kosong");
            return;
        }
        else if (oktet3.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Oktet 3 masih kosong");
            return;
        }
        else if (oktet4.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Oktet 4 masih kosong");
            return;
        }
        
        oktett1=Integer.parseInt(oktet1.getText());
        oktett2=Integer.parseInt(oktet2.getText());
        oktett3=Integer.parseInt(oktet3.getText());
        oktett4=Integer.parseInt(oktet4.getText());
        
        if(oktett1>=0 && oktett1<=127 && oktett2>=0 && oktett2<=255 && oktett3>=0 && oktett3<=255 && oktett4>=0 && oktett4<=255){
            result="IP Kelas A";
            ResultClassIP.setText(result);
        }
        else if(oktett1>=128 && oktett1<=191 && oktett2>=0 && oktett2<=255 && oktett3>=0 && oktett3<=255 && oktett4>=0 && oktett4<=255){
            result="IP Kelas B";
            ResultClassIP.setText(result);
        }
        else if(oktett1>=192 && oktett1<=223 && oktett2>=0 && oktett2<=255 && oktett3>=0 && oktett3<=255 && oktett4>=0 && oktett4<=255){
            result="IP Kelas C";
            ResultClassIP.setText(result);
        }
        else if(oktett1>=224 && oktett1<=239 && oktett2>=0 && oktett2<=255 && oktett3>=0 && oktett3<=255 && oktett4>=0 && oktett4<=255){
            result="IP Kelas D";
            ResultClassIP.setText(result);
        }
        else if(oktett1>=240 && oktett1<=255 && oktett2>=0 && oktett2<=255 && oktett3>=0 && oktett3<=255 && oktett4>=0 && oktett4<=255){
            result="IP Kelas E";
            ResultClassIP.setText(result);
        }
        else{
            result="IP tidak valid";
            ResultClassIP.setText(result);
        }
    }//GEN-LAST:event_BtnDetectIPActionPerformed

    private void btnPindahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPindahActionPerformed
        // TODO add your handling code here:
        new HalamanKe2().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPindahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelasIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelasIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelasIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelasIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelasIP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDetectIP;
    private javax.swing.JLabel ResultClassIP;
    private javax.swing.JButton btnPindah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField oktet1;
    private javax.swing.JTextField oktet2;
    private javax.swing.JTextField oktet3;
    private javax.swing.JTextField oktet4;
    // End of variables declaration//GEN-END:variables
}
